# Generated by Django 5.2.5 on 2025-08-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_driverhistory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='current_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='current_lng',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='rider',
            old_name='current_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='rider',
            old_name='current_lng',
            new_name='longitude',
        ),
    ]
